### ISSUE TITLE
FEATURE replace silverstripe-elemental-blocks with recipe-silverstripe-elemental-base-site

### ISSUE THREAD

**Issue by jsirish** [dynamic/recipe-silverstripe-base-site#15]
**Is your feature request related to a problem? Please describe.**
Currently all sites running `recipe-silverstripe-base-site` pull in a large number of blocks, many of which aren't used. Can generate a lot of extra front end work.

**Describe the solution you'd like**
Looking for a solution that only includes commonly used blocks by default, with other blocks pulled in specific to the project.

Created `dynamic/recipe-silverstripe-elemental-base-site` to include only these blocks:

* [dynamic/silverstripe-elemental-blog](https://github.com/dynamic/silverstripe-elemental-blog) ^2.0
* [dynamic/silverstripe-elemental-embedded-code](https://github.com/dynamic/silverstripe-elemental-embedded-code) ^2.0
* [dynamic/silverstripe-elemental-features](https://github.com/dynamic/silverstripe-elemental-features) ^2.0
* [dynamic/silverstripe-elemental-filelist](https://github.com/dynamic/silverstripe-elemental-filelist) ^2.0
* [dynamic/silverstripe-elemental-flexslider](https://github.com/dynamic/silverstripe-elemental-flexslider) ^2.0
* [dynamic/silverstripe-elemental-image](https://github.com/dynamic/silverstripe-elemental-image) ^2.0
* [dynamic/silverstripe-elemental-oembed](https://github.com/dynamic/silverstripe-elemental-oembed) ^2.0
* [dynamic/silverstripe-elemental-promos](https://github.com/dynamic/silverstripe-elemental-promos) ^2.0

This would replace `dynamic/silverstripe-elemental-blocks` and remove the following blocks from all projects, unless required in the composer file for the project:

* dynamic/silverstripe-elemental-accordion ^2.0
* dynamic/silverstripe-elemental-countdown ^2.0
* dynamic/silverstripe-elemental-customer-service ^2.0
* dynamic/silverstripe-elemental-gallery ^2.0
* dynamic/silverstripe-elemental-section-navigation ^2.0
* dynamic/silverstripe-elemental-sponsors ^2.0
* dynamic/silverstripe-elemental-tabset ^2.0
* dynamic/silverstripe-elemental-testimonials ^2.0

`recipe-silverstripe-base-site` currently does not have a release. However there are two near-launch sites running it as dev-master. The question is whether this can be done prior to a 1.0.0 tag, or if we tag the current version 1.0.0. If the latter, would this change be a 1.1 or a 2.0?

If we include this change in 1.0.0, we could leverage the content block report in the CMS to see what blocks are being used in the two projects prior to the update. If any blocks were to be removed via updating recipe-silverstripe-base-site, they would be added to composer requirements as part of the PR in the project. 

If the change comes after 1.0.0, we would simply update the requirements in each project to prevent updating to the breaking change release.

**Describe alternatives you've considered**
Removing block recipes and just including a list of commonly used blocks.

**Comment by jsirish** [comment]
New module is here https://github.com/dynamic/recipe-silverstripe-elemental-base-site

**Comment by muskie9** [comment]
I think a stable release with current state, then this being a minor release with a section noting the change in the README will work.

Any existing projects using the `1.0` line would need to update from `^` to `~` for the constraint of this module to prevent accidentally losing blocks.

This change could then be released as `1.1`. I'm not sure of the expectation of recipes following semvar, so if we're concerned about breaking semvar we could do a `2.0`.

**Comment by jsirish** [comment]
all makes sense. I'll do 1.0 for current version, 1.1 for the new. I'll add a list of removed blocks in the docs with the 1.1 release.
